// Источник данных по нейроанатомии (рабочая тетрадь, 18 занятий).
// Термины сгруппированы в 6 крупных тем. Латынь — Terminologia Anatomica
// (составлена вручную, требует сверки). Используется src/build.js.

const neuroCategories = [
  { key: "neuro_forebrain", title: "Большой мозг и ядра",      icon: "🧠" },
  { key: "neuro_midbrain",  title: "Промежуточный и средний мозг", icon: "💠" },
  { key: "neuro_hindbrain", title: "Задний и продолговатый мозг",  icon: "🌀" },
  { key: "neuro_pathways",  title: "Проводящие пути",          icon: "🔀" },
  { key: "neuro_nerves",    title: "Черепные нервы",           icon: "⚡" },
  { key: "neuro_senses",    title: "Органы чувств и покров",   icon: "👁️" },
];

const neuroTerms = {
  // ================= Тема 1: Большой мозг и базальные ядра (занятия 1, 2, 3) =================
  neuro_forebrain: [
    // Занятие 1 — Отделы головного мозга. Корешки ЧМН на основании
    { ru: "Продольная щель большого мозга", la: "fissura longitudinalis cerebri" },
    { ru: "Поперечная щель большого мозга", la: "fissura transversa cerebri" },
    { ru: "Обонятельная луковица", la: "bulbus olfactorius" },
    { ru: "Обонятельный тракт", la: "tractus olfactorius" },
    { ru: "Обонятельный треугольник", la: "trigonum olfactorium" },
    { ru: "Решетчатые отверстия решетчатой кости", la: "foramina cribrosa ossis ethmoidalis" },
    { ru: "Переднее продырявленное вещество", la: "substantia perforata anterior" },
    { ru: "Зрительный канал", la: "canalis opticus" },
    { ru: "Зрительный перекрест", la: "chiasma opticum" },
    { ru: "Зрительный тракт", la: "tractus opticus" },
    { ru: "Зрительный нерв", la: "nervus opticus" },
    { ru: "Серый бугор", la: "tuber cinereum" },
    { ru: "Воронка", la: "infundibulum" },
    { ru: "Сосцевидное тело", la: "corpus mamillare" },
    { ru: "Ножка мозга", la: "pedunculus cerebri" },
    { ru: "Межножковая ямка", la: "fossa interpeduncularis" },
    { ru: "Заднее продырявленное вещество", la: "substantia perforata posterior" },
    { ru: "Глазодвигательный нерв", la: "nervus oculomotorius" },
    { ru: "Промежуточный мозг", la: "diencephalon" },
    { ru: "Средний мозг", la: "mesencephalon" },
    { ru: "Задний мозг", la: "rhombencephalon" },
    { ru: "Мост", la: "pons" },
    { ru: "Средняя мозжечковая ножка", la: "pedunculus cerebellaris medius" },
    { ru: "Тройничный нерв", la: "nervus trigeminus" },
    { ru: "Пирамида", la: "pyramis medullae oblongatae" },
    { ru: "Олива", la: "oliva" },
    { ru: "Отводящий нерв", la: "nervus abducens" },
    { ru: "Яремное отверстие", la: "foramen jugulare" },
    { ru: "Лицевой нерв", la: "nervus facialis" },
    { ru: "Преддверно-улитковый нерв", la: "nervus vestibulocochlearis" },
    { ru: "Языкоглоточный нерв", la: "nervus glossopharyngeus" },
    { ru: "Блуждающий нерв", la: "nervus vagus" },
    { ru: "Добавочный нерв", la: "nervus accessorius" },
    { ru: "Подъязычный нерв", la: "nervus hypoglossus" },
    { ru: "Ствол головного мозга", la: "truncus encephali" },
    { ru: "Лобная доля полушария", la: "lobus frontalis hemispherii cerebri" },
    { ru: "Височная доля полушария", la: "lobus temporalis hemispherii cerebri" },
    { ru: "Теменная доля полушария", la: "lobus parietalis hemispherii cerebri" },
    { ru: "Затылочная доля полушария", la: "lobus occipitalis hemispherii cerebri" },
    { ru: "Островковая доля полушария", la: "lobus insularis hemispherii cerebri" },
    // Занятие 2 — Полушария большого мозга. Плащ. Обонятельный мозг
    { ru: "Лобный полюс полушарий мозга", la: "polus frontalis hemispherii cerebri" },
    { ru: "Затылочный полюс полушарий мозга", la: "polus occipitalis hemispherii cerebri" },
    { ru: "Височный полюс полушарий мозга", la: "polus temporalis hemispherii cerebri" },
    { ru: "Центральная борозда", la: "sulcus centralis" },
    { ru: "Латеральная борозда", la: "sulcus lateralis" },
    { ru: "Предцентральная борозда", la: "sulcus precentralis" },
    { ru: "Постцентральная борозда", la: "sulcus postcentralis" },
    { ru: "Верхняя и нижняя лобные борозды", la: "sulci frontales superior et inferior" },
    { ru: "Верхняя и средняя лобные извилины", la: "gyri frontales superior et medius" },
    { ru: "Покрышечная часть лобной доли", la: "pars opercularis lobi frontalis" },
    { ru: "Треугольная часть лобной доли", la: "pars triangularis lobi frontalis" },
    { ru: "Верхняя теменная долька", la: "lobulus parietalis superior" },
    { ru: "Нижняя теменная долька", la: "lobulus parietalis inferior" },
    { ru: "Верхняя височная борозда", la: "sulcus temporalis superior" },
    { ru: "Нижняя височная борозда", la: "sulcus temporalis inferior" },
    { ru: "Внутритеменная борозда", la: "sulcus intraparietalis" },
    { ru: "Надкраевая извилина", la: "gyrus supramarginalis" },
    { ru: "Угловая извилина", la: "gyrus angularis" },
    { ru: "Верхняя височная извилина", la: "gyrus temporalis superior" },
    { ru: "Нижняя височная извилина", la: "gyrus temporalis inferior" },
    { ru: "Средняя височная извилина", la: "gyrus temporalis medius" },
    { ru: "Борозда мозолистого тела", la: "sulcus corporis callosi" },
    { ru: "Поясная борозда", la: "sulcus cinguli" },
    { ru: "Поясная извилина", la: "gyrus cinguli" },
    { ru: "Парагиппокампальная извилина", la: "gyrus parahippocampalis" },
    { ru: "Сводчатая извилина", la: "gyrus fornicatus" },
    { ru: "Парацентральная долька", la: "lobulus paracentralis" },
    { ru: "Предклинье", la: "precuneus" },
    { ru: "Клин", la: "cuneus" },
    { ru: "Шпорная борозда", la: "sulcus calcarinus" },
    { ru: "Язычная извилина", la: "gyrus lingualis" },
    { ru: "Коллатеральная борозда", la: "sulcus collateralis" },
    { ru: "Прямая извилина", la: "gyrus rectus" },
    { ru: "Крючок", la: "uncus" },
    { ru: "Глазничные борозды", la: "sulci orbitales" },
    { ru: "Обонятельная борозда", la: "sulcus olfactorius" },
    { ru: "Медиальная затылочно-височная извилина", la: "gyrus occipitotemporalis medialis" },
    { ru: "Латеральная затылочно-височная извилина", la: "gyrus occipitotemporalis lateralis" },
    { ru: "Перешеек поясной извилины", la: "isthmus gyri cinguli" },
    { ru: "Постцентральная извилина", la: "gyrus postcentralis" },
    // Занятие 3 — Базальные ядра. Боковой желудочек
    { ru: "Мозолистое тело", la: "corpus callosum" },
    { ru: "Валик мозолистого тела", la: "splenium corporis callosi" },
    { ru: "Ствол мозолистого тела", la: "truncus corporis callosi" },
    { ru: "Колено мозолистого тела", la: "genu corporis callosi" },
    { ru: "Клюв мозолистого тела", la: "rostrum corporis callosi" },
    { ru: "Серый покров мозолистого тела", la: "indusium griseum" },
    { ru: "Лучистость мозолистого тела", la: "radiatio corporis callosi" },
    { ru: "Терминальная пластинка", la: "lamina terminalis" },
    { ru: "Тело свода мозга", la: "corpus fornicis" },
    { ru: "Столб свода мозга", la: "columna fornicis" },
    { ru: "Ножка свода", la: "crus fornicis" },
    { ru: "Спайка свода", la: "commissura fornicis" },
    { ru: "Передняя спайка", la: "commissura anterior" },
    { ru: "Прозрачная перегородка", la: "septum pellucidum" },
    { ru: "Полость прозрачной перегородки (пятый желудочек)", la: "cavum septi pellucidi" },
    { ru: "Межжелудочковое отверстие", la: "foramen interventriculare" },
    { ru: "Полосатое тело", la: "corpus striatum" },
    { ru: "Головка хвостатого ядра", la: "caput nuclei caudati" },
    { ru: "Чечевицеобразное ядро", la: "nucleus lentiformis" },
    { ru: "Медиальная мозговая пластинка", la: "lamina medullaris medialis" },
    { ru: "Латеральная мозговая пластинка", la: "lamina medullaris lateralis" },
    { ru: "Скорлупа", la: "putamen" },
    { ru: "Ограда", la: "claustrum" },
    { ru: "Наружная капсула", la: "capsula externa" },
    { ru: "Самая наружная капсула", la: "capsula extrema" },
    { ru: "Передняя ножка внутренней капсулы", la: "crus anterius capsulae internae" },
    { ru: "Задняя ножка внутренней капсулы", la: "crus posterius capsulae internae" },
    { ru: "Колено внутренней капсулы", la: "genu capsulae internae" },
    { ru: "Морской конек", la: "hippocampus" },
    { ru: "Пальцы ног морского конька", la: "pes hippocampi" },
    { ru: "Коллатеральный треугольник", la: "trigonum collaterale" },
    { ru: "Коллатеральное возвышение", la: "eminentia collateralis" },
    { ru: "Лобный рог бокового желудочка", la: "cornu frontale ventriculi lateralis" },
    { ru: "Центральная часть бокового желудочка", la: "pars centralis ventriculi lateralis" },
    { ru: "Концевая полоска", la: "stria terminalis" },
    { ru: "Затылочный рог бокового желудочка", la: "cornu occipitale ventriculi lateralis" },
    { ru: "Луковица затылочного рога", la: "bulbus cornus occipitalis" },
    { ru: "Птичья шпора", la: "calcar avis" },
    { ru: "Височный рог бокового желудочка", la: "cornu temporale ventriculi lateralis" },
    { ru: "Бледный шар", la: "globus pallidus" },
  ],

  // ================= Тема 2: Промежуточный и средний мозг, желудочки (занятия 4, 7) =================
  neuro_midbrain: [
    // Занятие 4 — Промежуточный мозг. Средний мозг
    { ru: "Крыша среднего мозга", la: "tectum mesencephali" },
    { ru: "Верхние холмики", la: "colliculi superiores" },
    { ru: "Нижние холмики", la: "colliculi inferiores" },
    { ru: "Ручка верхнего холмика", la: "brachium colliculi superioris" },
    { ru: "Ручка нижнего холмика", la: "brachium colliculi inferioris" },
    { ru: "Глазодвигательная борозда", la: "sulcus oculomotorius" },
    { ru: "Черное вещество среднего мозга", la: "substantia nigra mesencephali" },
    { ru: "Основание ножки мозга", la: "basis pedunculi cerebri" },
    { ru: "Межножковая ямка", la: "fossa interpeduncularis" },
    { ru: "Заднее продырявленное вещество", la: "substantia perforata posterior" },
    { ru: "Водопровод среднего мозга", la: "aqueductus mesencephali" },
    { ru: "Медиальное коленчатое тело", la: "corpus geniculatum mediale" },
    { ru: "Латеральное коленчатое тело", la: "corpus geniculatum laterale" },
    { ru: "Шишковидное тело", la: "corpus pineale" },
    { ru: "Поводки", la: "habenulae" },
    { ru: "Треугольники поводков", la: "trigona habenularia" },
    { ru: "Зрительный бугор", la: "thalamus" },
    { ru: "Передний бугорок таламуса", la: "tuberculum anterius thalami" },
    { ru: "Подушка таламуса", la: "pulvinar thalami" },
    { ru: "Межжелудочковое отверстие", la: "foramen interventriculare" },
    { ru: "Межталамическое сращение", la: "adhesio interthalamica" },
    { ru: "Гипоталамическая борозда", la: "sulcus hypothalamicus" },
    { ru: "Сосудистое сплетение III желудочка", la: "plexus choroideus ventriculi tertii" },
    { ru: "Полость третьего желудочка мозга", la: "cavitas ventriculi tertii cerebri" },
    { ru: "Собственно гипоталамическая область", la: "regio hypothalamica propria" },
    { ru: "Зрительный перекрест", la: "chiasma opticum" },
    { ru: "Зрительный тракт", la: "tractus opticus" },
    { ru: "Сосцевидные тела", la: "corpora mamillaria" },
    { ru: "Серый бугор", la: "tuber cinereum" },
    { ru: "Воронка", la: "infundibulum" },
    { ru: "Гипофиз", la: "hypophysis" },
    { ru: "Спинка турецкого седла", la: "dorsum sellae" },
    { ru: "Бугорок турецкого седла", la: "tuberculum sellae" },
    { ru: "Гипофизарная ямка", la: "fossa hypophysialis" },
    { ru: "Зрительный канал", la: "canalis opticus" },
    // Занятие 7 — Вентрикулярная система мозга
    { ru: "Первый желудочек", la: "ventriculus primus" },
    { ru: "Второй желудочек", la: "ventriculus secundus" },
    { ru: "Третий желудочек", la: "ventriculus tertius" },
    { ru: "Передний рог бокового желудочка", la: "cornu anterius ventriculi lateralis" },
    { ru: "Нижний рог бокового желудочка", la: "cornu inferius ventriculi lateralis" },
    { ru: "Задний рог бокового желудочка", la: "cornu posterius ventriculi lateralis" },
    { ru: "Центральная часть бокового желудочка", la: "pars centralis ventriculi lateralis" },
    { ru: "Головка хвостатого ядра", la: "caput nuclei caudati" },
    { ru: "Тело хвостатого ядра", la: "corpus nuclei caudati" },
    { ru: "Прозрачная перегородка", la: "septum pellucidum" },
    { ru: "Тело свода", la: "corpus fornicis" },
    { ru: "Столбы свода", la: "columnae fornicis" },
    { ru: "Гиппокамп", la: "hippocampus" },
    { ru: "Коллатеральное возвышение", la: "eminentia collateralis" },
    { ru: "Коллатеральный треугольник", la: "trigonum collaterale" },
    { ru: "Птичья шпора", la: "calcar avis" },
    { ru: "Полость прозрачных перегородок", la: "cavum septi pellucidi" },
    { ru: "Сосудистое сплетение бокового желудочка", la: "plexus choroideus ventriculi lateralis" },
  ],

  // ================= Тема 3: Задний и продолговатый мозг, ромбовидная ямка (занятия 5, 6, 8) =================
  neuro_hindbrain: [
    // Занятие 5 — Задний мозг
    { ru: "Вентральная поверхность моста", la: "facies ventralis pontis" },
    { ru: "Средняя мозжечковая ножка", la: "pedunculus cerebellaris medius" },
    { ru: "Нижняя мозжечковая ножка", la: "pedunculus cerebellaris inferior" },
    { ru: "Верхняя мозжечковая ножка", la: "pedunculus cerebellaris superior" },
    { ru: "Базилярная борозда моста", la: "sulcus basilaris pontis" },
    { ru: "Правое полушарие мозжечка", la: "hemispherium cerebelli dextrum" },
    { ru: "Левое полушарие мозжечка", la: "hemispherium cerebelli sinistrum" },
    { ru: "Червь", la: "vermis cerebelli" },
    { ru: "Зубчатое ядро мозжечка", la: "nucleus dentatus cerebelli" },
    { ru: "Центральная долька мозжечка", la: "lobulus centralis cerebelli" },
    { ru: "Четырехугольная долька", la: "lobulus quadrangularis" },
    { ru: "Лист червя", la: "folium vermis" },
    { ru: "Верхняя полулунная долька", la: "lobulus semilunaris superior" },
    { ru: "Нижняя полулунная долька", la: "lobulus semilunaris inferior" },
    { ru: "Двубрюшная долька", la: "lobulus biventer" },
    { ru: "Миндалина мозжечка", la: "tonsilla cerebelli" },
    { ru: "Долинка мозжечка", la: "vallecula cerebelli" },
    { ru: "Пирамида червя", la: "pyramis vermis" },
    { ru: "Клочок", la: "flocculus" },
    { ru: "Вершина червя", la: "culmen vermis" },
    { ru: "Скат червя", la: "declive vermis" },
    { ru: "Передняя вырезка мозжечка", la: "incisura anterior cerebelli" },
    { ru: "Поперечная щель мозга", la: "fissura transversa cerebri" },
    { ru: "Корешок VI пары ЧМН", la: "radix nervi abducentis" },
    { ru: "Корешок VII пары ЧМН", la: "radix nervi facialis" },
    { ru: "Корешок VIII пары ЧМН", la: "radix nervi vestibulocochlearis" },
    { ru: "Корешок V пары ЧМН", la: "radix nervi trigemini" },
    { ru: "Горизонтальная щель мозжечка", la: "fissura horizontalis cerebelli" },
    { ru: "Скат затылочной кости", la: "clivus" },
    { ru: "Задняя черепная ямка", la: "fossa cranii posterior" },
    // Занятие 6 — Продолговатый мозг
    { ru: "Передняя срединная щель", la: "fissura mediana anterior" },
    { ru: "Задняя срединная борозда", la: "sulcus medianus posterior" },
    { ru: "Переднелатеральная борозда", la: "sulcus anterolateralis" },
    { ru: "Подъязычный канал", la: "canalis nervi hypoglossi" },
    { ru: "Вентральная поверхность продолговатого мозга", la: "facies ventralis medullae oblongatae" },
    { ru: "Дорсальная поверхность продолговатого мозга", la: "facies dorsalis medullae oblongatae" },
    { ru: "Пирамиды", la: "pyramides medullae oblongatae" },
    { ru: "Олива", la: "oliva" },
    { ru: "Тонкий пучок", la: "fasciculus gracilis" },
    { ru: "Клиновидный пучок", la: "fasciculus cuneatus" },
    { ru: "Бугорок тонкого ядра", la: "tuberculum gracile" },
    { ru: "Бугорок клиновидного ядра", la: "tuberculum cuneatum" },
    { ru: "Позадиоливная борозда", la: "sulcus retroolivaris" },
    { ru: "Корешок языкоглоточного нерва", la: "radix nervi glossopharyngei" },
    { ru: "Корешок блуждающего нерва", la: "radix nervi vagi" },
    { ru: "Корешок добавочного нерва", la: "radix nervi accessorii" },
    { ru: "Корешок подъязычного нерва", la: "radix nervi hypoglossi" },
    { ru: "Ромбовидная ямка", la: "fossa rhomboidea" },
    { ru: "IV желудочек", la: "ventriculus quartus" },
    { ru: "Верхний мозговой парус", la: "velum medullare superius" },
    { ru: "Верхние мозжечковые ножки", la: "pedunculi cerebellares superiores" },
    { ru: "Нижний мозговой парус", la: "velum medullare inferius" },
    { ru: "Нижние мозжечковые ножки", la: "pedunculi cerebellares inferiores" },
    { ru: "Средние мозжечковые ножки", la: "pedunculi cerebellares medii" },
    // Занятие 8 — Ромбовидная ямка
    { ru: "Срединная борозда ромбовидной ямки", la: "sulcus medianus fossae rhomboideae" },
    { ru: "Лицевой бугорок", la: "colliculus facialis" },
    { ru: "Вестибулярное поле", la: "area vestibularis" },
    { ru: "Треугольник блуждающего нерва", la: "trigonum nervi vagi" },
    { ru: "Задвижка", la: "obex" },
    { ru: "Медиальное возвышение", la: "eminentia medialis" },
    { ru: "Треугольник подъязычного нерва", la: "trigonum nervi hypoglossi" },
    { ru: "Мозговые полоски", la: "striae medullares ventriculi quarti" },
    { ru: "Латеральные карманы", la: "recessus laterales ventriculi quarti" },
    { ru: "Пограничная борозда", la: "sulcus limitans" },
    { ru: "Краниальная ямка", la: "fovea cranialis" },
    { ru: "Каудальная ямка", la: "fovea caudalis" },
    { ru: "Голубоватое место", la: "locus coeruleus" },
    { ru: "Двигательное ядро тройничного нерва", la: "nucleus motorius nervi trigemini" },
    { ru: "Чувствительное ядро тройничного нерва", la: "nucleus sensorius nervi trigemini" },
    { ru: "Двигательное ядро отводящего нерва", la: "nucleus motorius nervi abducentis" },
    { ru: "Двигательное ядро лицевого нерва", la: "nucleus motorius nervi facialis" },
    { ru: "Ядро одиночного пути", la: "nucleus tractus solitarii" },
    { ru: "Верхнее слюноотделительное ядро", la: "nucleus salivatorius superior" },
    { ru: "Переднее улитковое ядро", la: "nucleus cochlearis anterior" },
    { ru: "Заднее улитковое ядро", la: "nucleus cochlearis posterior" },
    { ru: "Медиальное вестибулярное ядро", la: "nucleus vestibularis medialis" },
    { ru: "Латеральное вестибулярное ядро", la: "nucleus vestibularis lateralis" },
    { ru: "Верхнее вестибулярное ядро", la: "nucleus vestibularis superior" },
    { ru: "Нижнее вестибулярное ядро", la: "nucleus vestibularis inferior" },
    { ru: "Двойное ядро", la: "nucleus ambiguus" },
    { ru: "Нижнее слюноотделительное ядро", la: "nucleus salivatorius inferior" },
    { ru: "Заднее ядро блуждающего нерва", la: "nucleus dorsalis nervi vagi" },
    { ru: "Двигательное ядро добавочного нерва", la: "nucleus motorius nervi accessorii" },
    { ru: "Ядро подъязычного нерва", la: "nucleus nervi hypoglossi" },
  ],

  // ================= Тема 4: Проводящие пути (занятия 9, 10) =================
  neuro_pathways: [
    // Занятие 9 — Проводящие пути (1)
    { ru: "Постцентральная извилина", la: "gyrus postcentralis" },
    { ru: "Верхняя теменная долька", la: "lobulus parietalis superior" },
    { ru: "Нижняя теменная долька", la: "lobulus parietalis inferior" },
    { ru: "Таламус", la: "thalamus" },
    { ru: "Мост", la: "pons" },
    { ru: "Верхние мозжечковые ножки", la: "pedunculi cerebellares superiores" },
    { ru: "Нижние мозжечковые ножки", la: "pedunculi cerebellares inferiores" },
    { ru: "Червь мозжечка", la: "vermis cerebelli" },
    { ru: "Боковой канатик спинного мозга", la: "funiculus lateralis medullae spinalis" },
    { ru: "Передний канатик спинного мозга", la: "funiculus anterior medullae spinalis" },
    { ru: "Задний канатик спинного мозга", la: "funiculus posterior medullae spinalis" },
    { ru: "Пучок Голля", la: "fasciculus gracilis" },
    { ru: "Пучок Бурдаха", la: "fasciculus cuneatus" },
    { ru: "Задний рог спинного мозга", la: "cornu posterius medullae spinalis" },
    { ru: "Передний рог спинного мозга", la: "cornu anterius medullae spinalis" },
    { ru: "Боковой рог спинного мозга", la: "cornu laterale medullae spinalis" },
    { ru: "Задний корешок спинного мозга", la: "radix posterior nervi spinalis" },
    { ru: "Грудное ядро спинного мозга", la: "nucleus thoracicus posterior" },
    { ru: "Спинномозговой ганглий", la: "ganglion spinale" },
    { ru: "Пирамида продолговатого мозга", la: "pyramis medullae oblongatae" },
    { ru: "Внутренняя капсула", la: "capsula interna" },
    { ru: "Передняя ножка внутренней капсулы", la: "crus anterius capsulae internae" },
    { ru: "Ромбовидная ямка", la: "fossa rhomboidea" },
    { ru: "Олива", la: "oliva" },
    { ru: "Продолговатый мозг", la: "medulla oblongata" },
    { ru: "Задняя ножка внутренней капсулы", la: "crus posterius capsulae internae" },
    { ru: "Латеральный спинно-таламический путь", la: "tractus spinothalamicus lateralis" },
    { ru: "Передний спинно-таламический путь", la: "tractus spinothalamicus anterior" },
    { ru: "Передний спиномозжечковый путь", la: "tractus spinocerebellaris anterior" },
    { ru: "Задний спиномозжечковый путь", la: "tractus spinocerebellaris posterior" },
    // Занятие 10 — Проводящие пути (2)
    { ru: "Предцентральная извилина", la: "gyrus precentralis" },
    { ru: "Средний мозг", la: "mesencephalon" },
    { ru: "Верхние холмики", la: "colliculi superiores" },
    { ru: "Нижние холмики", la: "colliculi inferiores" },
    { ru: "Основание ножки мозга", la: "basis pedunculi cerebri" },
    { ru: "Красное ядро", la: "nucleus ruber" },
    { ru: "Покрышка среднего мозга", la: "tegmentum mesencephali" },
    { ru: "Ствол мозга", la: "truncus encephali" },
    { ru: "Латеральное вестибулярное ядро продолговатого мозга", la: "nucleus vestibularis lateralis" },
    { ru: "Нижнее вестибулярное ядро мозга", la: "nucleus vestibularis inferior" },
    { ru: "Перекрёст пирамид", la: "decussatio pyramidum" },
    { ru: "Колено внутренней капсулы", la: "genu capsulae internae" },
    { ru: "Двигательное ядро III пары ЧМН", la: "nucleus nervi oculomotorii" },
    { ru: "Полушария мозжечка", la: "hemispheria cerebelli" },
    { ru: "Средняя ножка мозжечка", la: "pedunculus cerebellaris medius" },
    { ru: "Корково-ядерный путь", la: "tractus corticonuclearis" },
    { ru: "Латеральный корково-спинномозговой путь", la: "tractus corticospinalis lateralis" },
    { ru: "Передний корково-спинномозговой путь", la: "tractus corticospinalis anterior" },
    { ru: "Красноядерно-спинномозговой путь", la: "tractus rubrospinalis" },
    { ru: "Тектоспинальный путь", la: "tractus tectospinalis" },
    { ru: "Ретикуло-спинномозговой путь", la: "tractus reticulospinalis" },
    { ru: "Преддверно-спинномозговой путь", la: "tractus vestibulospinalis" },
  ],

  // ================= Тема 5: Черепные нервы (занятия 12, 13, 14) =================
  neuro_nerves: [
    // Занятие 12 — I–IV пары ЧМН
    { ru: "Внутриглазная часть зрительного нерва", la: "pars intraocularis nervi optici" },
    { ru: "Внутриглазничная часть зрительного нерва", la: "pars orbitalis nervi optici" },
    { ru: "Канальцевая часть зрительного нерва", la: "pars intracanalicularis nervi optici" },
    { ru: "Внутричерепная часть зрительного нерва", la: "pars intracranialis nervi optici" },
    { ru: "Зрительный тракт", la: "tractus opticus" },
    { ru: "Зрительный перекрест", la: "chiasma opticum" },
    { ru: "Зрительный канал", la: "canalis opticus" },
    { ru: "Латеральные коленчатые тела", la: "corpora geniculata lateralia" },
    { ru: "Шпорная борозда", la: "sulcus calcarinus" },
    { ru: "Обонятельный нерв", la: "nervus olfactorius" },
    { ru: "Обонятельный тракт", la: "tractus olfactorius" },
    { ru: "Обонятельный треугольник", la: "trigonum olfactorium" },
    { ru: "Переднее продырявленное вещество", la: "substantia perforata anterior" },
    { ru: "Парагиппокампальная извилина", la: "gyrus parahippocampalis" },
    { ru: "Сводчатая извилина", la: "gyrus fornicatus" },
    { ru: "Крючок", la: "uncus" },
    { ru: "Решетчатые отверстия", la: "foramina cribrosa" },
    { ru: "Решетчатая пластинка решетчатой кости", la: "lamina cribrosa ossis ethmoidalis" },
    { ru: "Верхний носовой ход", la: "meatus nasi superior" },
    { ru: "Обонятельная область полости носа", la: "regio olfactoria cavitatis nasi" },
    { ru: "Глазодвигательный нерв", la: "nervus oculomotorius" },
    { ru: "Глазодвигательная борозда", la: "sulcus oculomotorius" },
    { ru: "Верхняя глазничная щель", la: "fissura orbitalis superior" },
    { ru: "Блоковый нерв", la: "nervus trochlearis" },
    { ru: "Добавочное ядро глазодвигательного нерва", la: "nucleus accessorius nervi oculomotorii" },
    { ru: "Двигательное ядро глазодвигательного нерва", la: "nucleus nervi oculomotorii" },
    { ru: "Двигательное ядро блокового нерва", la: "nucleus nervi trochlearis" },
    { ru: "Глазница", la: "orbita" },
    { ru: "Нижняя косая мышца глаза", la: "musculus obliquus inferior bulbi" },
    { ru: "Верхняя прямая мышца глаза", la: "musculus rectus superior bulbi" },
    { ru: "Нижняя прямая мышца глаза", la: "musculus rectus inferior bulbi" },
    { ru: "Латеральная прямая мышца глаза", la: "musculus rectus lateralis bulbi" },
    // Занятие 13 — V–VII пары ЧМН
    { ru: "Тройничный нерв", la: "nervus trigeminus" },
    { ru: "Среднемозговое ядро тройничного нерва", la: "nucleus mesencephalicus nervi trigemini" },
    { ru: "Мостовое ядро тройничного нерва", la: "nucleus pontinus nervi trigemini" },
    { ru: "Спинномозговое ядро тройничного нерва", la: "nucleus spinalis nervi trigemini" },
    { ru: "Вдавление тройничного нерва пирамиды височной кости", la: "impressio trigeminalis" },
    { ru: "Верхняя глазничная щель клиновидной кости", la: "fissura orbitalis superior ossis sphenoidalis" },
    { ru: "Круглое отверстие клиновидной кости", la: "foramen rotundum" },
    { ru: "Овальное отверстие клиновидной кости", la: "foramen ovale" },
    { ru: "Глазной нерв", la: "nervus ophthalmicus" },
    { ru: "Лобный нерв", la: "nervus frontalis" },
    { ru: "Носоресничный нерв", la: "nervus nasociliaris" },
    { ru: "Слезный нерв", la: "nervus lacrimalis" },
    { ru: "Надглазничный нерв", la: "nervus supraorbitalis" },
    { ru: "Верхнечелюстной нерв", la: "nervus maxillaris" },
    { ru: "Подглазничный нерв", la: "nervus infraorbitalis" },
    { ru: "Скуловой нерв", la: "nervus zygomaticus" },
    { ru: "Малая гусиная лапка", la: "pes anserinus minor" },
    { ru: "Наружные носовые нервы", la: "rami nasales externi" },
    { ru: "Внутренние носовые нервы", la: "rami nasales interni" },
    { ru: "Скулолицевой нерв", la: "ramus zygomaticofacialis" },
    { ru: "Нижнеальвеолярный нерв", la: "nervus alveolaris inferior" },
    { ru: "Язычный нерв", la: "nervus lingualis" },
    { ru: "Щечный нерв нижнечелюстного нерва", la: "nervus buccalis" },
    { ru: "Ушно-височный нерв", la: "nervus auriculotemporalis" },
    { ru: "Отводящий нерв", la: "nervus abducens" },
    { ru: "Ядро отводящего нерва", la: "nucleus nervi abducentis" },
    { ru: "Расщелина большого каменистого нерва височной кости", la: "hiatus canalis nervi petrosi majoris" },
    { ru: "Борозда большого каменистого нерва височной кости", la: "sulcus nervi petrosi majoris" },
    { ru: "Лицевой нерв", la: "nervus facialis" },
    { ru: "Двигательное ядро лицевого нерва", la: "nucleus motorius nervi facialis" },
    { ru: "Верхнее слюноотделительное ядро лицевого нерва", la: "nucleus salivatorius superior" },
    { ru: "Ядро одиночного пути", la: "nucleus tractus solitarii" },
    { ru: "Шилососцевидное отверстие", la: "foramen stylomastoideum" },
    { ru: "Большая гусиная лапка", la: "pes anserinus major" },
    { ru: "Скулоглазничное отверстие", la: "foramen zygomaticoorbitale" },
    { ru: "Щечная ветвь лицевого нерва", la: "rami buccales nervi facialis" },
    { ru: "Краевая ветвь нижней челюсти", la: "ramus marginalis mandibulae" },
    { ru: "Шейная ветвь лицевого нерва", la: "ramus colli nervi facialis" },
    { ru: "Поверхностная шейная петля", la: "ansa cervicalis superficialis" },
    // Занятие 14 — VIII–XII пары ЧМН
    { ru: "Языкоглоточный нерв", la: "nervus glossopharyngeus" },
    { ru: "Блуждающий нерв", la: "nervus vagus" },
    { ru: "Двойное ядро", la: "nucleus ambiguus" },
    { ru: "Нижнее слюноотделительное ядро", la: "nucleus salivatorius inferior" },
    { ru: "Заднее ядро блуждающего нерва", la: "nucleus dorsalis nervi vagi" },
    { ru: "Добавочный нерв", la: "nervus accessorius" },
    { ru: "Ядро добавочного нерва", la: "nucleus nervi accessorii" },
    { ru: "Подъязычный нерв", la: "nervus hypoglossus" },
    { ru: "Ядро подъязычного нерва", la: "nucleus nervi hypoglossi" },
    { ru: "Треугольник подъязычного нерва", la: "trigonum nervi hypoglossi" },
    { ru: "Яремное отверстие", la: "foramen jugulare" },
    { ru: "Каменистая ямочка", la: "fossula petrosa" },
    { ru: "Расщелина малого каменистого нерва", la: "hiatus canalis nervi petrosi minoris" },
    { ru: "Передняя поверхность пирамиды височной кости", la: "facies anterior partis petrosae ossis temporalis" },
    { ru: "Барабанно-сосцевидная щель", la: "fissura tympanomastoidea" },
    { ru: "Сосцевидный каналец височной кости", la: "canaliculus mastoideus" },
    { ru: "Бифуркация общей сонной артерии", la: "bifurcatio carotidis" },
    { ru: "Возвратный гортанный нерв", la: "nervus laryngeus recurrens" },
    { ru: "Грудино-ключично-сосцевидная мышца", la: "musculus sternocleidomastoideus" },
    { ru: "Трапециевидная мышца", la: "musculus trapezius" },
    { ru: "Задняя латеральная борозда продолговатого мозга", la: "sulcus posterolateralis medullae oblongatae" },
    { ru: "Поднижнечелюстной треугольник", la: "trigonum submandibulare" },
    { ru: "Язычный треугольник", la: "trigonum linguale" },
  ],

  // ================= Тема 6: Органы чувств и общий покров (занятия 15, 16, 17, 18) =================
  neuro_senses: [
    // Занятие 15 — Орган зрения
    { ru: "Роговица", la: "cornea" },
    { ru: "Склера", la: "sclera" },
    { ru: "Собственная сосудистая оболочка", la: "choroidea" },
    { ru: "Ресничное тело", la: "corpus ciliare" },
    { ru: "Радужка", la: "iris" },
    { ru: "Хрусталик", la: "lens" },
    { ru: "Передняя камера глаза", la: "camera anterior bulbi" },
    { ru: "Задняя камера глаза", la: "camera posterior bulbi" },
    { ru: "Стекловидное тело", la: "corpus vitreum" },
    { ru: "Верхняя косая мышца глазного яблока", la: "musculus obliquus superior bulbi" },
    { ru: "Нижняя косая мышца глазного яблока", la: "musculus obliquus inferior bulbi" },
    { ru: "Боковая прямая мышца глазного яблока", la: "musculus rectus lateralis bulbi" },
    { ru: "Внутренняя прямая мышца глазного яблока", la: "musculus rectus medialis bulbi" },
    { ru: "Нижняя прямая мышца глазного яблока", la: "musculus rectus inferior bulbi" },
    { ru: "Верхняя прямая мышца глазного яблока", la: "musculus rectus superior bulbi" },
    { ru: "Передний полюс глазного яблока", la: "polus anterior bulbi oculi" },
    { ru: "Задний полюс глазного яблока", la: "polus posterior bulbi oculi" },
    { ru: "Веко верхнее", la: "palpebra superior" },
    { ru: "Веко нижнее", la: "palpebra inferior" },
    { ru: "Конъюнктива", la: "tunica conjunctiva" },
    { ru: "Носослезный канал", la: "canalis nasolacrimalis" },
    { ru: "Зрительный нерв", la: "nervus opticus" },
    { ru: "Зрительный тракт", la: "tractus opticus" },
    { ru: "Зрительный перекрест", la: "chiasma opticum" },
    { ru: "Слепое пятно", la: "discus nervi optici" },
    { ru: "Центральная ямка сетчатки", la: "fovea centralis retinae" },
    { ru: "Ядро глазного яблока", la: "nucleus bulbi oculi" },
    { ru: "Слепая часть сетчатки", la: "pars caeca retinae" },
    { ru: "Зрительная часть сетчатки", la: "pars optica retinae" },
    { ru: "Ресничный поясок", la: "zonula ciliaris" },
    { ru: "Мышца, поднимающая верхнее веко", la: "musculus levator palpebrae superioris" },
    { ru: "Зрительный канал", la: "canalis opticus" },
    { ru: "Зрачок", la: "pupilla" },
    { ru: "Передний полюс хрусталика", la: "polus anterior lentis" },
    { ru: "Задний полюс хрусталика", la: "polus posterior lentis" },
    // Занятие 16 — Орган слуха и равновесия
    { ru: "Ушная раковина", la: "auricula" },
    { ru: "Наружный слуховой проход", la: "meatus acusticus externus" },
    { ru: "Ладья", la: "scapha" },
    { ru: "Завиток", la: "helix" },
    { ru: "Противозавиток", la: "antihelix" },
    { ru: "Ножка противозавитка", la: "crus antihelicis" },
    { ru: "Треугольная ямка", la: "fossa triangularis auriculae" },
    { ru: "Козелок", la: "tragus" },
    { ru: "Противокозелок", la: "antitragus" },
    { ru: "Мочка", la: "lobulus auriculae" },
    { ru: "Молоточек", la: "malleus" },
    { ru: "Головка молоточка", la: "caput mallei" },
    { ru: "Рукоятка молоточка", la: "manubrium mallei" },
    { ru: "Наковальня", la: "incus" },
    { ru: "Короткая ножка наковальни", la: "crus breve incudis" },
    { ru: "Длинная ножка наковальни", la: "crus longum incudis" },
    { ru: "Стремя", la: "stapes" },
    { ru: "Головка стремени", la: "caput stapedis" },
    { ru: "Передняя ножка стремени", la: "crus anterius stapedis" },
    { ru: "Задняя ножка стремени", la: "crus posterius stapedis" },
    { ru: "Основание стремени", la: "basis stapedis" },
    { ru: "Барабанная полость", la: "cavitas tympani" },
    { ru: "Барабанная перепонка", la: "membrana tympanica" },
    { ru: "Слуховая труба", la: "tuba auditiva" },
    { ru: "Глоточное отверстие слуховой трубы", la: "ostium pharyngeum tubae auditivae" },
    { ru: "Внутренний слуховой проход", la: "meatus acusticus internus" },
    { ru: "Костный лабиринт внутреннего уха", la: "labyrinthus osseus" },
    { ru: "Перепончатый лабиринт внутреннего уха", la: "labyrinthus membranaceus" },
    { ru: "Передний полукружный канал", la: "canalis semicircularis anterior" },
    { ru: "Задний полукружный канал", la: "canalis semicircularis posterior" },
    { ru: "Латеральный полукружный канал", la: "canalis semicircularis lateralis" },
    { ru: "Сферический мешочек", la: "sacculus" },
    { ru: "Эллиптический мешочек", la: "utriculus" },
    { ru: "Преддверье", la: "vestibulum" },
    { ru: "Базилярная пластинка", la: "lamina basilaris" },
    { ru: "Кортиев орган", la: "organum spirale" },
    { ru: "Лестница преддверия", la: "scala vestibuli" },
    { ru: "Барабанная лестница", la: "scala tympani" },
    { ru: "Улитка", la: "cochlea" },
    { ru: "Преддверно-улитковый нерв", la: "nervus vestibulocochlearis" },
    // Занятие 17 — Органы вкуса и обоняния
    { ru: "Язык", la: "lingua" },
    { ru: "Листовидные сосочки", la: "papillae foliatae" },
    { ru: "Нитевидные сосочки", la: "papillae filiformes" },
    { ru: "Грибовидные сосочки", la: "papillae fungiformes" },
    { ru: "Желобоватые сосочки", la: "papillae vallatae" },
    { ru: "Слепое отверстие", la: "foramen caecum linguae" },
    { ru: "Верхушка языка", la: "apex linguae" },
    { ru: "Тело языка", la: "corpus linguae" },
    { ru: "Спинка языка", la: "dorsum linguae" },
    { ru: "Лицевой нерв", la: "nervus facialis" },
    { ru: "Языкоглоточный нерв", la: "nervus glossopharyngeus" },
    { ru: "Блуждающий нерв", la: "nervus vagus" },
    { ru: "Нижняя продольная мышца языка", la: "musculus longitudinalis inferior" },
    { ru: "Поперечная мышца языка", la: "musculus transversus linguae" },
    { ru: "Вертикальная мышца языка", la: "musculus verticalis linguae" },
    { ru: "Верхняя носовая раковина", la: "concha nasalis superior" },
    { ru: "Средняя носовая раковина", la: "concha nasalis media" },
    { ru: "Перегородка носа", la: "septum nasi" },
    { ru: "Гиппокамп", la: "hippocampus" },
    { ru: "Сосцевидные тела", la: "corpora mamillaria" },
    { ru: "Обонятельный нерв", la: "nervus olfactorius" },
    { ru: "Ядро одиночного пути", la: "nucleus tractus solitarii" },
    // Занятие 18 — Общий покров
    { ru: "Кожа", la: "cutis" },
    { ru: "Волосы", la: "pili" },
    { ru: "Ноготь", la: "unguis" },
    { ru: "Брови", la: "supercilia" },
    { ru: "Сальная железа", la: "glandula sebacea" },
    { ru: "Потовая железа", la: "glandula sudorifera" },
  ],
};

module.exports = { neuroCategories, neuroTerms };
